MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.entity;
namespace MvcStok.Controllers

{
    public class UrunController : Controller
    {
        // GET: Urun
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLurunler.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler = (from i in db.TBLkategori.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()

                                             }
                                             ).ToList();
            ViewBag.dgr = degerler;                       
            return View();
        }
        [HttpPost]
        public ActionResult UrunEkle(TBLurunler p1) 
        {
            var ktg = db.TBLkategori.Where(m => m.KATEGORIID == p1.TBLkategori.KATEGORIID).FirstOrDefault();   // seçmiş oldugumuz ilk degeri bize getirir.
            p1.TBLkategori = ktg;
            db.TBLurunler.Add(p1);             // add metodunu da ekleme için kullan.
            db.SaveChanges();

            return RedirectToAction("Index");  // bizi kaydetme işlemini gerçekleşirdikten sonra index sayfasına yönlendirsin
        }
        public ActionResult SIL(int id)
        {
            var urun = db.TBLurunler.Find(id);     // find komutu ile bul remove komutu ile kaldır
            db.TBLurunler.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLurunler.Find(id);

            List<SelectListItem> degerler = (from i in db.TBLkategori.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()

                                             }
                                            ).ToList();
            ViewBag.dgr = degerler;

            return View("UrunGetir", urun);
        }
        public ActionResult Guncelle(TBLurunler p)
        {

            var urun = db.TBLurunler.Find(p.URUNID);
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT =p.FIYAT;
            //urun katogori katası verilen değerler uyuşmuyor.
            urun.URUNKATEGORI = p.URUNKATEGORI;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.entity
@model List<TBLurunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th> Urun ID</th>
        <th> Urun Adı</th>
        <th> Markası</th>
        <th> Kategori</th>
        <th> Fiyat</th>
        <th> Stok</th>
        <th>SİL</th>
        <th>Güncelle</th>

    </tr>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>

                <td> @urn.URUNID</td>
                <td> @urn.URUNAD</td>
                <td> @urn.MARKA</td>
                <td> @urn.TBLkategori.KATEGORIAD</td>
                <td> @urn.FIYAT</td>
                <td> @urn.STOK</td>
                <td><a href="/URUN/SIL/@urn.URUNID" class="btn btn-warning">SİL</a></td>
                <td><a href="/URUN/UrunGetir/@urn.URUNID" class="btn btn-success">GÜNCELLE</a></td> 
            </tr>
        }
    </tbody>
</table>
<a href="/URUN/UrunEkle/"class="btn btn-primary">YENI ÜRÜN</a>

MvcStok/Views/Urun/UrunEkle.cshtml
@model MvcStok.Models.entity.TBLurunler
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="URUNAD" />
    </div>

    <div>
        <label>Markası</label>
        <input type="text" class="form-control" name="MARKA" />
    </div>
    <div>
        <label>Kategori Seçiniz</label>
        @Html.DropDownListFor(m=>m.TBLkategori.KATEGORIID,(List<SelectListItem>)ViewBag.dgr,new { @class="form-control"})
    </div>
    <div>
        <label>Fiyatı</label>
        <input type="text" class="form-control" name="FIYAT" />
    </div>
    <div>
        <label>Stok Adet</label>
        <input type="text" class="form-control" name="STOK" />
    </div>
    <div style="margin-top:15px">
        <button class="btyn btn-info">Ürün Ekle</button>
    </div>
</form>

MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.entity.TBLurunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Urun Getir Sayfası</h2>



@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.URUNID)
    @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNAD)
    @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MARKA)
    @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNKATEGORI)
    @Html.DropDownListFor(m=>m.TBLkategori.KATEGORIID,(List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    @*@Html.TextBoxFor(m => m.URUNKATEGORI, new { @class = "form-control" })*@
    <br />
    @Html.LabelFor(m => m.FIYAT)
    @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.STOK)
    @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })

</div>
    <div>
        <button class="btn btn-warning">Ürün Güncelle</button>
    </div>

}