MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.entity;
namespace MvcStok.Controllers

{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLmusteriler.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLmusteriler p1)
        {
            if (!ModelState.IsValid)    
            {
                return View("YeniMusteri");  
            }
            db.TBLmusteriler.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var musteri = db.TBLmusteriler.Find(id);
            db.TBLmusteriler.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLmusteriler.Find(id);
            return View("MusteriGetir", mus);
        }
        public ActionResult Guncelle(TBLmusteriler p1)
        {
            var musteri = db.TBLmusteriler.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.entity
@model List<TBLmusteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th> Musterı ID</th>
        <th> Musteri Adı</th>
        <th> Musteri Soyadı</th>
        <th>SİL</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach (var mus in Model)
        {
        <tr>

            <th> @mus.MUSTERIID</th>
            <td> @mus.MUSTERIAD</td>
            <td> @mus.MUSTERISOYAD</td>
            <td><a href="/MUSTERI/SIL/@mus.MUSTERIID" class="btn btn-danger">SİL</a></td>
            <td><a href="/MUSTERI/MusteriGetir/@mus.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
        </tr>
        }
        </tbody>
    </table>
<a href="/Musteri/YeniMusteri/" class="btn btn-primary">YENI MÜŞTERİ EKLE</a>

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.entity.TBLmusteriler
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Müsteri Adı</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-class" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:blue" })
    </div>

    <div>
        <label>Müsteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div>
    <div style="margin-top:15px">
        <button class="btyn btn-info">Müşteri Ekle</button>
    </div>
</form>

MvcStok/Views/Musteri/musteriGetir.cshtml
@model MvcStok.Models.entity.TBLmusteriler
@{
    ViewBag.Title = "musteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Müşteri Getir !</h2>


@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.MUSTERIID)
    @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERIAD)
    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERISOYAD)
    @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })

</div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>
    </div>

}