MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.entity; //entity klasörüne ulaş

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLkategori.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniKategori()  //sadece sayfayı gri dödürme işlemi yap diyor.
        {         
            return View();                                    
        }
                                                     // !!! htppget ve htppPost un temel amacı işlem yapılmayan durumlarda veriyi entegre etmemek .eğer edilirse gereksiz bir iş olur.
        [HttpPost] //örneğin kaydet butonuna bastıgım zaman kaydet işlemini gerçekleştir demek için kullanıyoruz.
         public ActionResult YeniKategori(TBLkategori p1)
        {
            if(!ModelState.IsValid)    //! ekledik
            {
                return View("YeniKategori");  //YeniKategori şeklinde yazdık
            }
            db.TBLkategori.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var kategori = db.TBLkategori.Find(id);
            db.TBLkategori.Remove(kategori);     // kategoriden gelen degeri silecek.
            db.SaveChanges();                   // değişiklikleri kaydet.
            return RedirectToAction("Index");  // yönlendrme yapar index sayfasına
     
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TBLkategori.Find(id);
            return View("KategoriGetir", ktgr);
        }
        public ActionResult Guncelle(TBLkategori p1)
        {
            var ktg = db.TBLkategori.Find(p1.KATEGORIID);
            ktg.KATEGORIAD = p1.KATEGORIAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.entity
@model List<TBLkategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<table class="table table-bordered" >
    <tr>
        <th>KATEGORI ID</th> 
        <th>KATEGORI AD</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach(var ktgr in Model)
            {
           <tr>
               <th>@ktgr.KATEGORIID</th>
               <td>@ktgr.KATEGORIAD</td>
               <td><a href="/KATEGORI/SIL/@ktgr.KATEGORIID" class="btn btn-danger">SİL</a></td>
               <td><a href="/KATEGORI/KategoriGetir/@ktgr.KATEGORIID"class="btn btn-success">GÜNCELLE</a></td>

           </tr>
                 }
    </tbody>
    </table>
<a href="/KATEGORI/Yenikategori/"class="btn btn-primary">YENI KATEGORI EKLE</a>

MvcStok/Views/Kategori/KategoriGetir.cshtml
@model MvcStok.Models.entity.TBLkategori
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";                // Başlangıçta null değer döndürdüğünden dolayı programı buradan başlatamayız.
}

@using(Html.BeginForm("Guncelle","Kategori",FormMethod.Post))
            {
       <div class="form-group">
           @Html.LabelFor(m=>m.KATEGORIID)
           @Html.TextBoxFor(m=>m.KATEGORIID, new { @class="form-control" })
           <br/>
           <br/>
           @Html.LabelFor(m=>m.KATEGORIAD)
           @Html.TextBoxFor(m=>m.KATEGORIAD,new { @class="form-control"}) 

                </div>
           <div>
               <button class="btn btn-warning">Kategori Güncelle</button>
           </div>
        }

MvcStok/Views/Kategori/YeniKategori.cshtml
@model MvcStok.Models.entity.TBLkategori
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    @*<div>
        <label>Kategori Adı</label>
        <input type="text" class="form-control" name="KATEGORIAD" />
    </div>*@
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m=>m.KATEGORIAD,new { @class="form-class"})
        @Html.ValidationMessageFor(m=>m.KATEGORIAD,"",new {@style="color:purple"})
    </div>
    <div style="margin-top:25px">
        <button class="btn btn-info">Kategori Ekle</button>
    </div>
</form>